---
driver:
  name: dokken
  chef_version: 12.21.14

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
  - name: ubuntu-17.04
    driver:
      image: dokken/ubuntu-17.04
      pid_one_command: /bin/systemd
  - name: debian-8.9
    driver:
      image: dokken/debian-8

suites:
  - name: default
    run_list:
      - role[ubiktest]
    verifier:
      inspec_tests:
        -
    excludes:
      - debian-8.9

# disabled as ubilinux repos 
# confuses apt
#  - name: upboard
#    run_list:
#      - role[upik]
#    verifier:
#      inspec_tests:
#        -
#    attributes:
#      upik:
#        skip_mounts: true
#      user:
#        gid: 1002
#        uid: 1002
#    excludes:
#      - ubuntu-16.04
#      - ubuntu-17.04
