---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd

  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd

suites:
  - name: ubik
    run_list:
      - role[ubiktest]
    verifier:
      inspec_tests:
        - path: tests/integration/ubik/

  - name: marvin
    run_list:
      - role[marvintest]
    verifier:
      inspec_tests:
        - path: tests/integration/ubik/
