---
driver:
  name: vagrant
  provider: virtualbox
  cachier: true

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
    driver:
      box: ubuntu/xenial64
  - name: ubuntu-17.10
    driver:
      box: ubuntu/zesty64

suites:
  - name: ubik
    run_list:
      - role[ubiktest]
    verifier:
      inspec_tests:
        - path: tests/integration/ubik/
  - name: marvin
    run_list:
      - role[marvintest]
    verifier:
      inspec_tests:
        - path: tests/integration/ubik/
    excludes:
      - ubuntu-17.10
