version: 2
jobs:
  test_1604:
    machine: true
    steps:
      - checkout

      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: bundle exec inspec vendor tests/integration/ubik
      - run: 
          command: bundle exec kitchen test default-ubuntu-1604
          no_output_timeout: 1200

  test_1704:
    machine: true
    steps:
      - checkout

      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: bundle exec inspec vendor tests/integration/ubik
      - run:
          command: bundle exec kitchen test default-ubuntu-1704
          no_output_timeout: 1200

workflows:
  version: 2
  converge:
    jobs:
      - test_1604
      - test_1704
