version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: bundle exec kitchen test
