version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
jobs:
  style:
    docker:
      - image: 'cimg/ruby:2.7'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          check-path: site-cookbooks roles
          label: Inspecting with Rubocop
      - run:
          command: bundle exec foodcritic -B site-cookbooks -R roles

  ubik_2004:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - ruby/install-deps

      - run:
          command: bundle exec inspec vendor tests/integration/ubik
          environment:
            BUNDLE_GEMFILE: .circleci/Gemfile

      - run:
          command: bundle exec kitchen test ubik-ubuntu-2004
          no_output_timeout: 1200
          environment:
            KITCHEN_YAML: .kitchen.ci.yml
            BUNDLE_GEMFILE: .circleci/Gemfile

  marvin_2004:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: bundle exec inspec vendor tests/integration/ubik
          environment:
            BUNDLE_GEMFILE: .circleci/Gemfile

      - run:
          command: bundle exec kitchen test marvin-ubuntu-2004
          no_output_timeout: 1200
          environment:
            KITCHEN_YAML: .kitchen.ci.yml
            BUNDLE_GEMFILE: .circleci/Gemfile

  bender_2004:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout

      - run:
          command: bundle exec inspec vendor tests/integration/ubik
          environment:
            BUNDLE_GEMFILE: .circleci/Gemfile

      - run:
          command: bundle exec kitchen test bender-ubuntu-2004
          no_output_timeout: 1200
          environment:
            KITCHEN_YAML: .kitchen.ci.yml
            BUNDLE_GEMFILE: .circleci/Gemfile

workflows:
  version: 2
  converge:
    jobs:
      - style
      # - ubik_2004:
      #     requires:
      #       - style
      - marvin_2004:
          requires:
            - style
      # - bender_2004:
      #     requires:
      #       - style
